### ISSUE TITLE
[Active] Remember Me Now

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#140]
Zero charge, breaks on use
Teleports the player one stage earlier
(Special effect on the basement one ?)
Treasure and shop pool

**Comment by dedChar** [comment]
Maybe it could clear all rooms if used in Basement I?

**Comment by ProbablyTez** [comment]
Maybe yeah, I was thinking about something really special, like trigger a bonus secret ending

**Comment by dedChar** [comment]
Oh what if, once the API allows the creation of custom floors, the player will be teleported into Isaac's House? He should start in the living room. In the living room are a tv, a sofa and two items. One item would be "Isaac's Toys" and the other would be "Isaac's Underwear". Not sure what these do, but they should be pretty good. These two items are there because that's everything Isaac's Mom takes away from him in the intro. 
One room would be the kitchen. There should be Mom's Knife in it.
Other rooms are Isaac's and Mom's Bedrooms and a bathroom maybe.
Isaac's room should feature his bed and a trapdoor into basement with a rug pushed to the side.
Mom's bedroom should feature some of Mom's items.

**Comment by ProbablyTez** [comment]
Yeah that's a fun idea for a lil easter egg
Impossible to do right now sadly, but fun nonetheless ^^
