### ISSUE TITLE
[Eternal Pooter] Makes his regular attack as well

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#246]
This issue will happen with any entity who'se attacks aren't linekd to events in the anm2

a way to fix this would be to give every entity the same subtype (is 15 nto used at all in the base game ?) and delete any regular projectile coming from entities with this subtype

EDIT: 15 doesn't seem to be used at all the base game

**Comment by dedChar** [comment]
The problem with that is, that there is no (or at least I haven't found one) way to detect if the projectile (or any entity for that matter) originated from a specific subtype of entity. Type and Variant are easy to detect.
One would think that `Entity::SpawnerEntity` or `Entity::Parent` could do the job since, in theory, they would contain the whole entity and thus its subtype, but these are most of the time just `nil` when it comes to something nicalis coded. And of course there are `Entity::SpawnerType` and `Entity::SpawnerVariant`, which both work most of the time when `Entity::SpawnerEntity` is `nil`, but there is no `Entity::SpawnerSubType`. :/

**Comment by ProbablyTez** [comment]
Yeah  wasn't able to make it work either.
Well, worst case scenario we'll have to remake the entity from scratch

**Comment by dedChar** [comment]
setting `Entity::ProjectileDelay` to -1 seems to fix it

**Comment by ProbablyTez** [comment]
Great!
