### ISSUE TITLE
[Passive] Stink Eye

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#350]
### Art
- [x] Costume Sprite
- [x] Collectible Sprite
- [x] Note Sprite
- [x] Tear Sprite

Idea Card : #341

**Comment by Floofball** [comment]
Costume: http://imgur.com/a/A5XjL

Collectible: http://imgur.com/a/Rd5PA

Note: http://imgur.com/a/jQcnt

Tear: Just using the brown tear sprite (Mega Fatty's, for example), should be fine. Otherwise, just let me know where I can find a sprite sheet and I'll work on it.

P.S, I hope this isn't too much of a hassle, but the Stinky! effect probably shouldn't affect any of the poop-based enemies. That's about it, though.

**Comment by ProbablyTez** [comment]
Here's a sprite sheet for the tears ! http://i.imgur.com/q0uuCTD.png
Mega Fatty's tears are always the same size so we can't really use those 😉

**Comment by Floofball** [comment]
Alrighty, here are the tear sprites: http://imgur.com/a/tUdSZ

If the corn is a bit too much, just let me known and I'll just change them to be brown and lumpy instead.
