### ISSUE TITLE
Eternal foetus

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#44]
Flies around, teleports and converts other enemies into their eternal versions

**Comment by dedChar** [comment]
I've been thinking about this one, and if my thought process is correct, then we'll need to set the subtype of whatever enemy it flies over to 15 and then reload the graphics, the same way we do in the random spawn of eternal enemies.
The problem is, that they have their animation file path hard coded. So we'll need to create some function that takes an ID, a variant and a subtype and then returns the name of the entity with the given IDs.
I was thinking of creating a table that contains every name and the corresponding IDs. This sounds very tedious to do though.
Maybe you know something more efficient, @ProbablyTez ?

**Comment by ProbablyTez** [comment]
I was trying to build a list of all eternal alts and their names by reading the xml's but actually buidlign the table is much simpler

Everytime we add a new alt, just do
```
table.insert(EternalsList, Type);
table.insert(EternalsList, Variant);
table.insert(EternalsList, "Name");
```
That's not that bad!

NOTE: Ended up wiritng a function do that but still the same shit

Also changed the name of the entity
